// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['WEB_APIKEY']!,
    appId: '1:291626094648:web:300b96d4048e6c6aa096cd',
    messagingSenderId: '291626094648',
    projectId: 'robochat-d515b',
    authDomain: 'robochat-d515b.firebaseapp.com',
    storageBucket: 'robochat-d515b.appspot.com',
    measurementId: 'G-91LW0XGGBQ',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['ANDROID_APIKEY']!,
    appId: '1:291626094648:android:6db2fc516084fe45a096cd',
    messagingSenderId: '291626094648',
    projectId: 'robochat-d515b',
    storageBucket: 'robochat-d515b.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['IOS_APIKEY']!,
    appId: '1:291626094648:ios:4e07d315c81677eba096cd',
    messagingSenderId: '291626094648',
    projectId: 'robochat-d515b',
    storageBucket: 'robochat-d515b.appspot.com',
    iosBundleId: 'com.example.robochat',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['MAC_APIKEY']!,
    appId: '1:291626094648:ios:143794c3cdaef262a096cd',
    messagingSenderId: '291626094648',
    projectId: 'robochat-d515b',
    storageBucket: 'robochat-d515b.appspot.com',
    iosBundleId: 'com.example.robochat.RunnerTests',
  );
}
